version: "3"
services:

    php-fpm:
        image: bitnami/php-fpm:8.1
        volumes:
            - "${PROJECT_ROOT}/public:/var/www:cached"
            - "${PROJECT_ROOT}:/app"
            - "${PROJECT_ROOT}/var/composer-cache:/.composer:cached"
        environment:
            APP_ENV: ${APP_ENV}
            ENABLE_XDEBUG: 1
            XDEBUG_CONFIG: remote_enable=on remote_autostart=off remote_host=172.17.0.1 idekey=PHPSTORM
            PHP_MEMORY_LIMIT: -1
        user: ${USER_ID}:${GROUP_ID}

    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SomeRandomPasswordHere}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes: ###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###
