version: "3"
services:

    php-fpm:
        build:
            context: .
            dockerfile: .dev/Dockerfile-8.1
        command: php-fpm --allow-to-run-as-root
        volumes:
            - "${PROJECT_ROOT}:/var/www:cached"
            - "${PROJECT_ROOT}/var/composer-cache:/.composer:cached"
        environment:
            APP_ENV: ${APP_ENV}
            XDEBUG_MODE: "develop,debug"
            PHP_MEMORY_LIMIT: -1
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        user: ${USER_ID}:${GROUP_ID}
        hostname: 'billing.local'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            -   database

    swagger-ui:
        image: "swaggerapi/swagger-ui"
        volumes:
            - "${PROJECT_ROOT:-.}/openapi.v1.json:/usr/share/nginx/html/openapi.v1.json"
            - "${HOME:?err}/.ssh/known_hosts:/etc/ssh/ssh_known_hosts:ro"
        environment:
            URLS: '[{ url: "openapi.v1.json", name: "Api v1"}]'


    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SomeRandomPasswordHere}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes: ###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###

networks:
    default:
        driver: bridge
