# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Billing\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DataLayer/Entity/'
            - '../src/Kernel.php'
