FROM php:8.1-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev\
    git \
    zip \
    unzip

RUN docker-php-ext-install pdo pdo_pgsql

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug
ADD ./.dev/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

RUN curl https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony
